# Array Operations

In [79]:
import numpy as np

In [80]:
num = np.array([12,13,14,15,12,16])

In [81]:
print(num)

[12 13 14 15 12 16]


In [82]:
num.dtype

dtype('int32')

In [83]:
num.shape

(6,)

In [84]:
num[1]

13

In [85]:
num = np.array([12,13,14,15,12.3,16])

In [86]:
print(num)

[12.  13.  14.  15.  12.3 16. ]


In [87]:
num[1]

13.0

In [88]:
num = np.array([12,13,14,15,"Robin",16])

In [89]:
print(num)

['12' '13' '14' '15' 'Robin' '16']


In [90]:
num[1]

'13'

In [91]:
num.dtype

dtype('<U11')

In [92]:
ord("A")

65

In [93]:
chr(69)

'E'

In [94]:
line = "हॅलो रॉबिन कशी आहेस तू? "


In [95]:
print(line)

हॅलो रॉबिन कशी आहेस तू? 


In [96]:
line * 10

'हॅलो रॉबिन कशी आहेस तू? हॅलो रॉबिन कशी आहेस तू? हॅलो रॉबिन कशी आहेस तू? हॅलो रॉबिन कशी आहेस तू? हॅलो रॉबिन कशी आहेस तू? हॅलो रॉबिन कशी आहेस तू? हॅलो रॉबिन कशी आहेस तू? हॅलो रॉबिन कशी आहेस तू? हॅलो रॉबिन कशी आहेस तू? हॅलो रॉबिन कशी आहेस तू? '

In [97]:
line.startswith("ह")

True

In [98]:
line =np.array(["हॅलो","रॉबिन","कशी","आहेस","तू?"])


In [99]:
line

array(['हॅलो', 'रॉबिन', 'कशी', 'आहेस', 'तू?'], dtype='<U5')

In [100]:
num = np.array([56,12])
x = [56,12]

In [101]:
x*2

[56, 12, 56, 12]

In [102]:
num * 2

array([112,  24])

In [104]:
num >13

array([ True, False])

In [105]:
13 in num

False

In [106]:
13 not in num

True

In [108]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [109]:
np.ones(13)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [110]:
np.empty(5)

array([2.12199579e-314, 4.67296746e-307, 4.66397970e-321, 7.42698527e-312,
       3.69126375e-317])

In [111]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [113]:
list(range(2,15,3))

[2, 5, 8, 11, 14]

In [115]:
np.arange(2,15,3)

array([ 2,  5,  8, 11, 14])

In [118]:
np.arange(1,10,0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])

In [119]:
num.view


<function ndarray.view>

In [120]:
num.max()

56

In [123]:
num.mean()

34.0

In [124]:
num.argmax()

0

In [129]:
num.sort()

In [130]:
num

array([12, 56])

In [131]:
np.linspace(1,10,12)

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [139]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [140]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [141]:
x.shape


(3, 4)

In [142]:
x.size

12

In [144]:
x.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [145]:
x.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [146]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Series Operations

In [1]:
import pandas as pd


In [3]:
x = pd.Series([12,13,14,])
y = pd.Series(["k","o","d"])

In [4]:
df = pd.DataFrame({
    "roll":x,
    "name":y
})

In [5]:
df

roll name
0    12    k
1    13    o
2    14    d